### PR TITLE
Keyboard Scroll issue fix and placeholder

### PR DESCRIPTION
**Pull request by yamperboy**
- Add placeholder for location field
- Fix scrolling of results by up/down keys

### CODE REVIEW

**Comment by markathomas** [comment]
In all, great job! Just a few small tweaks and I'll merge it in.

**Comment by yamperboy** [comment]
Thank you Mark!!! Please let me know if you need me to change something...

**Comment by markathomas** [comment]
please see my comments on things to change

**Comment by yamperboy** [comment]
Hey Mark,

I've fixed the suggested elements. Please let me know your opinion or if you find any further problem.

Thanks for all your help.

**Pull request merged**
